### ISSUE TITLE
Unused Variables in Global Scope

### ISSUE THREAD

**Issue by eduardokraus** [Unitu/moodle-block_unitu_notif#1]
It has been detected that there are variables declared in the global scope that are not being used in the code. This can cause confusion, increase complexity, and impact system maintainability. It is recommended to review and remove these variables to improve code clarity and performance.

![Captura de Tela 2024-12-02 às 15 30 20](https://github.com/user-attachments/assets/17ad7368-7cd4-4046-a297-61813c3438f6)

**Comment by eduardokraus** [comment]
![Captura de Tela 2024-12-02 às 15 36 56](https://github.com/user-attachments/assets/147fd886-2410-4043-8f63-8f4cdbab4e24)

**Comment by eduardokraus** [comment]
![Captura de Tela 2024-12-02 às 15 37 55](https://github.com/user-attachments/assets/28fa1905-af04-4305-b57d-8685c49b8d9a)

**Comment by eduardokraus** [comment]
![Captura de Tela 2024-12-02 às 15 38 19](https://github.com/user-attachments/assets/c8bd46db-0bab-4a97-a868-6e1fa4ebf851)

**Comment by radzivil** [comment]
Addressed in https://github.com/Unitu/moodle-block_unitu_notif/pull/10
