### ISSUE TITLE
Fixing Indentation in the access.php File

### ISSUE THREAD

**Issue by eduardokraus** [Unitu/moodle-block_unitu_notif#3]
The access.php file is using an 8-character indentation, while the project's standard is 4 characters. This creates inconsistencies in the code and hampers readability.

![Captura de Tela 2024-12-02 às 15 34 31](https://github.com/user-attachments/assets/8e7af8e0-3c3f-4f5a-904a-b5c99a5c4e6e)

**Comment by radzivil** [comment]
This should be done with the Prettier.

**Comment by YacoubBadran** [comment]
Thank you for raising it @eduardokraus 
I did code styling on[ this PR](https://github.com/Unitu/moodle-block_unitu_notif/pull/9)

After carefully reviewing Moodle's coding style, I found that indentation is 4 but continuation indentation (wrapped line) is 8. You can take a look at these two sources:
https://moodledev.io/general/development/policies/codingstyle#wrapping-control-structures
https://github.com/enovation/moodle-utils/blob/master/phpstorm-config/Moodle.xml

**Comment by radzivil** [comment]
Thank you, @YacoubBadran! 
https://github.com/Unitu/moodle-block_unitu_notif/pull/9 merged
