### ISSUE TITLE
 Inspection Flags Zero Values with Unit of Measurement

### ISSUE THREAD

**Issue by eduardokraus** [Unitu/moodle-block_unitu_notif#4]
This inspection identifies and highlights entries where the value is zero but includes a specified unit of measurement. Ensure the data is reviewed to confirm whether zero is valid or requires correction.

![Captura de Tela 2024-12-02 às 15 39 21](https://github.com/user-attachments/assets/b14bf08f-2c5c-40d4-ae53-4bf6b3dfd4cf)

**Comment by radzivil** [comment]
@eduardokraus thank you for raising it. It has been now resolved.
