### ISSUE TITLE
Improve CSS Selector Specificity in Moodle Plugins

### ISSUE THREAD

**Issue by eduardokraus** [Unitu/moodle-block_unitu_notif#5]
All styles.css files from plugins are concatenated, cached, and served as a single resource across all Moodle pages. To prevent a plugin's styles from unintentionally affecting other parts of the platform, more specific CSS selectors are required.

For example, instead of using a generic selector like .contentarea, use a scoped selector such as .path-mod-mymodule .contentarea. The .path-* classes are automatically added to the HTML tags by Moodle's core renderers, ensuring that the plugin's CSS is restricted to its own context.

![Captura de Tela 2024-12-02 às 15 41 31](https://github.com/user-attachments/assets/144981e4-1622-46a9-8486-d14793057f7b)

**Comment by volodymyrdovhan** [comment]
Hello,

Your plugin's current selectors are not sufficiently namespaced, which can cause unintended styling issues in other areas of Moodle outside the plugin's scope.

Please revise the CSS selectors to ensure they are specific to your plugin, adhering to the requirement that they do not affect other parts of Moodle.
https://moodledev.io/general/community/plugincontribution/checklist#css-styles

Thanks

**Comment by radzivil** [comment]
@eduardokraus @volodymyrdovhan thank you for raising it. It has been now resolved.
